apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: 
  generateName: tekton-yaml-lint-pipelinerun-
spec:
  pipelineRef: 
    name: tekton-yaml-lint
  params:
    - name: url 
      value: https://github.com/cloud-native-garage-method-cohort/emea-cohort-8-fred-aklamanu-yaml
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec: 
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce


   